setwd("/media/shyam/external/multiome_clu_2/multi5")
library(Seurat)
library(Signac)
load("/media/shyam/external/multiome_clu_2/multi5/cluall_m5_0dpi_2dpi_dblt_filtd_rna_clustered_idented_peaks_recalled_genesLinked_chromvar_weighted_macs2peaks_embed_clustered_idented_cluster_formatted2_format3_chromvar2_jaspar2022only_newcollapse2_rezonationed_mean.RData")
Idents(clu) <- clu$new_rna_clusters
levels(clu)
levels(clu) <- c(grep('^RevSC', levels(clu), value = T) ,grep('^ICC', levels(clu), value = T),grep('^PC', levels(clu), value = T), 'EC-R5', 'EC-R7', 'EC-R4', 'EC-R1', 'EC-R17', 'EC-R10', 'EC-R2', 'EC-R3', 'EC-R9', 'EC-R6', 'EC-R18', 'EC-R21', grep('^GC', levels(clu), value = T), grep('^EE', levels(clu), value = T), grep('^TC', levels(clu), value = T),grep('^Fibro', levels(clu), value = T), grep('^Immune', levels(clu), value = T))
library(ggplot2)
df <- data.frame(rnaUMAP1 = Embeddings(clu, 'umap.rna')[,1], rnaUMAP2 = Embeddings(clu, 'umap.rna')[,2], ClusterNumber = clu$rna_clusters, ClusterName = clu$new_rna_clusters)
df_label <- df %>% group_by(ClusterNumber) %>% summarize(rnaUMAP1 = mean(rnaUMAP1), rnaUMAP2 = mean(rnaUMAP2))
library(tidyverse)
df <- data.frame(rnaUMAP1 = Embeddings(clu, 'umap.rna')[,1], rnaUMAP2 = Embeddings(clu, 'umap.rna')[,2], ClusterNumber = clu$rna_clusters, ClusterName = clu$new_rna_clusters)
df_label <- df %>% group_by(ClusterNumber) %>% summarize(rnaUMAP1 = mean(rnaUMAP1), rnaUMAP2 = mean(rnaUMAP2))
df$ClusterName <- factor(df$ClusterName, levels=levels(clu))
ggplot(df, aes(x = rnaUMAP1, y = rnaUMAP2)) + geom_point(shape = 16, aes(color = ClusterName), size = 1) + geom_text(data = df_label, aes(label = ClusterNumber)) + theme(panel.background = element_rect(fill = 'white'), axis.line = element_line(size = 1, color = 'black'), axis.text = element_text(size = 12), axis.title.x = element_text(size = 12), axis.title.y = element_text(size = 12), text = element_text(size = 12), legend.key = element_rect(fill = 'white')) + guides(color = guide_legend(override.aes = list(size = 3) ) ) + labs(color = 'WNN Clusters')
df <- data.frame(rnaUMAP1 = Embeddings(clu, 'umap.rna')[,1], rnaUMAP2 = Embeddings(clu, 'umap.rna')[,2], ClusterNumber = clu$rna_clusters, ClusterName = clu$new_rna_clusters)
df_label <- df %>% group_by(ClusterNumber) %>% summarize(rnaUMAP1 = mean(rnaUMAP1), rnaUMAP2 = mean(rnaUMAP2))
df$ClusterName <- factor(df$ClusterName, levels=levels(clu))
ggplot(df, aes(x = rnaUMAP1, y = rnaUMAP2)) + geom_point(shape = 16, aes(color = ClusterName), size = 0.5) + geom_text(data = df_label, aes(label = ClusterNumber)) + theme(panel.background = element_rect(fill = 'white'), axis.line = element_line(size = 1, color = 'black'), axis.text = element_text(size = 12), axis.title.x = element_text(size = 12), axis.title.y = element_text(size = 12), text = element_text(size = 12), legend.key = element_rect(fill = 'white')) + guides(color = guide_legend(override.aes = list(size = 3) ) ) + labs(color = 'RNA Clusters')
Idents(clu) <- clu$new_wnn_clusters
levels(clu)
levels(clu) <- c(grep('^RevSC', levels(clu), value = T) ,grep('^ICC', levels(clu), value = T),grep('^PC', levels(clu), value = T), 'EC-W1', 'EC-W2', 'EC-W10', 'EC-W14', 'EC-W4', 'EC-W7', 'EC-W11','EC-W5', 'EC-W3', grep('^GC', levels(clu), value = T), grep('^EE', levels(clu), value = T), grep('^TC', levels(clu), value = T),grep('^Fibro', levels(clu), value = T), grep('^Immune', levels(clu), value = T))
DimPlot(clu, reduction = 'wnn.umap', label = T)
cluwnn_vs_time_global <- as.data.frame(table(clu$new_wnn_clusters, clu$time))
for(i in unique(clu$time)){
cluwnn_vs_time_global[which(cluwnn_vs_time_global$Var2 == i),'prop'] <- cluwnn_vs_time_global[which(cluwnn_vs_time_global$Var2 == i),'Freq'] /length(WhichCells(clu, expression = time == i))
}
colnames(cluwnn_vs_time_global) <- c('Identity', 'Time', 'Freq', 'prop')
cluwnn_vs_time_global$Identity <- factor(cluwnn_vs_time_global$Identity, levels = levels(clu))
ggplot(cluwnn_vs_time_global, aes(fill = Time, y = prop, x = Identity)) + geom_bar(position = 'stack', stat = 'identity') + theme(text = element_text(size = 15, family = 'Helvetica'),axis.line = element_line(size = 1),axis.ticks = element_line(size = 1),panel.background = element_rect(fill = 'white'), axis.text.x = element_text(angle = 45, vjust = 1, hjust=1, size = 15)) + xlab('Identity') + ylab('Temporal Proportion') + scale_fill_manual(values = c('#2166ac', '#b2182b'))
cluwnn_vs_time <- as.data.frame(table(clu$new_wnn_clusters, clu$time))
for(i in unique(clu$new_wnn_clusters)){
cluwnn_vs_time[which(cluwnn_vs_time$Var1 == i),'prop'] <- cluwnn_vs_time[which(cluwnn_vs_time$Var1 == i),'Freq'] /length(WhichCells(clu, expression = new_wnn_clusters == i))
}
colnames(cluwnn_vs_time) <- c('Identity', 'Time', 'Freq', 'prop')
cluwnn_vs_time$Identity <- factor(cluwnn_vs_time$Identity, levels = levels(clu))
ggplot(cluwnn_vs_time, aes(fill = Time, y = prop, x = Identity)) + geom_bar(position = 'stack', stat = 'identity') + theme(text = element_text(size = 15, family = 'Helvetica'),axis.line = element_line(size = 1),axis.ticks = element_line(size = 1),panel.background = element_rect(fill = 'white'), axis.text.x = element_text(angle = 45, vjust = 1, hjust=1, size = 15)) + xlab('Identity') + ylab('Relative Temporal Proportion') + scale_fill_manual(values = c('#2166ac', '#b2182b'))
savehistory("/media/shyam/external/multiome_clu_2/multi5/tgfbeta_paper_apr092023_replotting_temporal_analysis_rna_umap.R")
