setwd("/media/shyam/external/multiome_clu_2/multi5")
library(Seurat)
library(Signac)
load("/media/shyam/external/multiome_clu_2/multi5/cluall_m5_0dpi_2dpi_dblt_filtd_rna_clustered_idented.RData")
Idents(clu) <- clu$rna_clusters_idents
DefaultAssay(clu) <- 'ATAC'
DimPlot(clu, reduction = 'umap.rna')
DimPlot(clu, reduction = 'umap.rna', label = T)
peaks <- CallPeaks(object = clu, group.by = 'rna_clusters_idented', macs2.path = '/home/shyam/anaconda3/envs/peaks_stuff/bin/macs2')
peaks <- CallPeaks(object = clu, group.by = 'rna_clusters_idents', macs2.path = '/home/shyam/anaconda3/envs/peaks_stuff/bin/macs2')
library(GenomeInfoDb)
library(BSgenome.Mmusculus.ensembl.mm39)
peaks2 <- keepStandardChromosomes(peaks, pruning.mode = 'coarse')
blacklist_mm39 <- read.csv(file = 'mm39_blacklist_frommm10_liftover.csv', header = F)
blacklist_mm39 <- as.data.frame(blacklist_mm39)
colnames(blacklist_mm39)
blacklist_mm39 <- makeGRangesFromDataFrame(blacklist_mm39, start.field = 'V2', end.field = 'V3', seqnames.field = 'V1', starts.in.df.are.0based = T)
blacklist_mm39 <- as.data.frame(blacklist_mm39)
blacklist_mm39$seqnames <-   str_replace(blacklist_mm39$seqnames, 'chr', "")
#for(i in grep("obj_", objects(), value = T)){
#  objj <- get(i)
#  objj <- subset(objj, subset = nFeature_spliced > 200)
#  assign(paste0("", i), objj)
#}
library(stringr)
blacklist_mm39$seqnames <-   str_replace(blacklist_mm39$seqnames, 'chr', "")
blacklist_mm39 <- makeGRangesFromDataFrame(blacklist_mm39, keep.extra.columns = T)
test <- as.data.frame(blacklist_mm39)
test$seqnames <-   str_replace(test$seqnames, 'chr', "")
test2 <- makeGRangesFromDataFrame(test, keep.extra.columns = T)
test2
rm(test)
rm(test2)
blacklists_chrs <- as.data.frame(blacklist_mm39)
blacklists_chrs$seqnames <-   str_replace(blacklists_chrs$seqnames, 'chr', "")
blacklists_chrs2 <- makeGRangesFromDataFrame(blacklists_chrs, keep.extra.columns = T)
save(peaks, file = 'cluall_multi5_rnaclusters_0_2dpi_dblt_filtd_macs2_peaksList.RData')
peaks <- subsetByOverlaps(peaks2, ranges = blacklists_chrs2, invert = TRUE)
macs2_counts <- FeatureMatrix(fragments = Fragments(clu), features = peaks, cells = colnames(clu))
clu[['peaks']] <-  CreateChromatinAssay(macs2_counts, fragments = Fragments(clu), annotation = Annotation(clu))
DefaultAssay(clu)
DefaultAssay(clu) <- 'peaks'
save(peaks, file = 'cluall_multi5_rnaclusters_0_2dpi_dblt_filtd_macs2_peaksList_subsetByOverlaps.RData')
save(clu, file = 'cluall_m5_0dpi_2dpi_dblt_filtd_rna_clustered_idented_peaks_recalled.RData')
savehistory("/media/shyam/external/multiome_clu_2/multi5/cluall_m5_0dpi_2dpi_dblt_filtd_rna_clustered_idented_peaks_recalled.R")
