setwd("/media/shyam/external/multiome_clu_2/multi5")
library(Seurat)
library(Signac)
load("/media/shyam/external/multiome_clu_2/multi5/cluall_m5_0dpi_2dpi_dblt_filtd_rna_clustered_idented_peaks_recalled.RData")
DefaultAssay(clu) <- 'peaks'
library(BSgenome.Mmusculus.ensembl.mm39)
clu <- RegionStats(clu, genome = BSgenome.Mmusculus.ensembl.mm39)
clu <- LinkPeaks(clu, peak.assay = 'peaks', expression.assay = 'RNA')
save(clu, file = 'cluall_m5_0dpi_2dpi_dblt_filtd_rna_clustered_idented_peaks_recalled_genesLinked.RData')
savehistory("/media/shyam/external/multiome_clu_2/multi5/cluall_m5_0dpi_2dpi_dblt_filtd_rna_clustered_idented_peaks_recalled_genesLinked.R")
library(Seurat)
library(Signac)
load(file = 'cluall_m5_0dpi_2dpi_dblt_filtd_rna_clustered_idented_peaks_recalled_genesLinked_chromvar.RData')
DefaultAssay(clu) <- 'peaks'
clu <- RunTFIDF(clu)
clu <- FindTopFeatures(clu, min.cutoff='q0')
clu <- RunSVD(clu)
clu <- RunUMAP(clu, reduction = 'lsi', dims= 2:30, reduction.name = 'umap.peaks', reduction.key = 'peakUMAP_', umap.method = 'umap-learn', metric = 'correlation')
clu <- FindMultiModalNeighbors(clu, reduction.list = list('pca','lsi'), dims.list = list(1:20, 2:30))
clu <- RunUMAP(clu, nn.name = 'weighted.nn', reduction.name = 'wnn.umap', reduction.key = 'wnnUMAP_')
DimPlot(clu, reduction = 'wnn.umap')
save(clu, file = 'cluall_m5_0dpi_2dpi_dblt_filtd_rna_clustered_idented_peaks_recalled_genesLinked_chromvar_weighted_macs2peaks_embed.RData')
savehistory(file = 'cluall_m5_0dpi_2dpi_dblt_filtd_rna_clustered_idented_peaks_recalled_genesLinked_chromvar_weighted_macs2peaks_embed.R')
