setwd("/media/shyam/external/multiome_clu_2/multi5")
library(Seurat)
library(Signac)
load("/media/shyam/external/multiome_clu_2/multi5/clu_0_2_dpi_new_collapsed_idents_zonationed.RData")
Idents(clu) <- clu$new_rna_clusters
DimPlot(clu, group.by = 'Doublet', reduction = 'umap.rna')
DimPlot(clu, label = T, reduction = 'umap.rna')
library(Seurat)
library(Signac)
load(file = 'cluall_multi5_0dpi_2dpi_preprocessed_dblt_filtd.RData')
DefaultAssay(clu) <- 'RNA'
clu <- FindVariableFeatures(clu, selection.method = 'vst', nfeatures = 2000)
clu <- ScaleData(clu)
clu <- RunPCA(clu, npcs = 50)
ElbowPlot(clu, ndims = 50)
clu <- RunUMAP(clu, dims = 1:20, metric = 'correlation', umap.method = 'umap-learn', reduction.key = 'rnaUMAP_', reduction.name = 'umap.rna')
clu <- FindNeighbors(clu, dims = 1:20, reduction = 'pca')
clu <- FindClusters(clu, resolution=seq(0.1,2.0, by = 0.1), graph.name = 'RNA_snn')
library(clustree)
clustree(clu, prefix = 'RNA_snn_res.')
clu <- FindClusters(clu, resolution = 1.3)
DimPlot(clu, reduction = 'umap.rna', label = T)
save(clu, file = 'cluall_m5_0dpi_2dpi_dblt_filtd_rna_clustered.RData')
savehistory(file = 'cluall_m5_0dpi_2dpi_dblt_filtd_rna_clustered.R')
