setwd("/media/shyam/external/multiome_clu_2/multi5")
library(Seurat)
library(Signac)
load("/media/shyam/external/multiome_clu_2/multi5/cluall_m5_0dpi_2dpi_dblt_filtd_rna_clustered_idented_peaks_recalled.RData")
DefaultAssay(clu) <- 'peaks'
library(BSgenome.Mmusculus.ensembl.mm39)
clu <- RegionStats(clu, genome = BSgenome.Mmusculus.ensembl.mm39)
clu <- LinkPeaks(clu, peak.assay = 'peaks', expression.assay = 'RNA')
save(clu, file = 'cluall_m5_0dpi_2dpi_dblt_filtd_rna_clustered_idented_peaks_recalled_genesLinked.RData')
savehistory("/media/shyam/external/multiome_clu_2/multi5/cluall_m5_0dpi_2dpi_dblt_filtd_rna_clustered_idented_peaks_recalled_genesLinked.R")
